---
abstract: 'Extract the presence or absence of a clinical condition from radiology reports. '
author:
  - 'Eduardo Iturrate <ed@iturrate.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-DxExtractor
no_index:
  directory:
    - t
    - inc
requires:
  Class::MakeMethods: 1
  Lingua::NegEx: 0.05
  Text::Sentence: 0.006
version: 1.08
