---
abstract: 'Perl extension to perform NER and quick and dirty checking for negation relying on StanfordCoreNLP. '
author:
  - 'root <root@localdomain>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-DxExtractor
no_index:
  directory:
    - t
    - inc
requires:
  Class::MakeMethods: 1
  Inline::Java: 0.053
  Lingua::StanfordCoreNLP: 0.04
version: 0.02
